name = "hugo-media-proxy"
main = "index.js"
compatibility_date = "2022-07-01"
route = "https://nicholas.cloud/media-proxy/*"
kv_namespaces = [
    { binding="CACHED_MEDIA", id="c976e3cbe4e24b8a8387e43ec4bf1236" },
]