name = "hero-of-time-link"
main = "index.ts"
compatibility_date = "2025-02-04"
compatibility_flags = [ "nodejs_compat" ]
route = "nicholas.cloud/goto*"
kv_namespaces = [
    { binding="SHORTCUTS", id="5504ea7cb33b4d2c908da38ebbb6ac29" }
]

secrets_store_secrets = [
  { store_id= "63609536ac1e446eb59160e3216e5f99", binding = "OTEL_EXPORTER_OTLP_ENDPOINT", secret_name = "OTEL_EXPORTER_OTLP_ENDPOINT" },
  { store_id= "63609536ac1e446eb59160e3216e5f99", binding = "OTEL_EXPORTER_OTLP_HEADERS", secret_name = "OTEL_EXPORTER_OTLP_HEADERS" }
]

[version_metadata]
binding = "CF_VERSION_METADATA"
