name = "terraform-registry"
main = "build/worker.js"
compatibility_date = "2022-07-01"
workers_dev = false
routes = [
    "https://nicholas.cloud/terraform-registry/*",
    "https://nicholas.cloud/.well-known/terraform.json",
]
