name = "terraform-registry"
main = "index.ts"
compatibility_date = "2025-02-04"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = false
routes = [
    "https://nicholas.cloud/terraform-registry/*",
    "https://nicholas.cloud/.well-known/terraform.json",
]

secrets_store_secrets = [
  { store_id= "63609536ac1e446eb59160e3216e5f99", binding = "OTEL_EXPORTER_OTLP_ENDPOINT", secret_name = "OTEL_EXPORTER_OTLP_ENDPOINT" },
  { store_id= "63609536ac1e446eb59160e3216e5f99", binding = "OTEL_EXPORTER_OTLP_HEADERS", secret_name = "OTEL_EXPORTER_OTLP_HEADERS" }
]

[version_metadata]
binding = "CF_VERSION_METADATA"
