name = "nchlswhttkr-dot-com"
main = "index.ts"
compatibility_date = "2025-02-04"
compatibility_flags = [ "nodejs_compat" ]
routes = [
    { pattern = "nchlswhttkr.com", custom_domain = true },
    { pattern = "blog.nchlswhttkr.com", custom_domain = true },
    { pattern = "resume.nchlswhttkr.com", custom_domain = true },
    { pattern = "source.nchlswhttkr.com", custom_domain = true },
    { pattern = "barhack.nchlswhttkr.com", custom_domain = true },
    { pattern = "www.nchlswhttkr.com", custom_domain = true },
    { pattern = "dalordish.nchlswhttkr.com", custom_domain = true }
]

secrets_store_secrets = [
  { store_id= "63609536ac1e446eb59160e3216e5f99", binding = "OTEL_EXPORTER_OTLP_ENDPOINT", secret_name = "OTEL_EXPORTER_OTLP_ENDPOINT" },
  { store_id= "63609536ac1e446eb59160e3216e5f99", binding = "OTEL_EXPORTER_OTLP_HEADERS", secret_name = "OTEL_EXPORTER_OTLP_HEADERS" }
]

[version_metadata]
binding = "CF_VERSION_METADATA"
