name = "honeycomb-buildkite-events-consumer"
main = "build/worker.js"
compatibility_date = "2022-07-01"
route = { pattern = "honeycomb-buildkite-events-consumer.nicholas.cloud", custom_domain = true }

[version_metadata]
binding = "CF_VERSION_METADATA"
