name = "bandcamp-mini-embed" # Doesn't match package, but deploys all components
main = "build/worker.js"
compatibility_date = "2025-02-04"
compatibility_flags = [ "nodejs_compat" ]
kv_namespaces = [
  { binding="ASSETS", id="471ada112ddd46eca4f652291d8f633e" }
]

[build]
watch_dir = "src"
command = "node esbuild.js"

[env.dev]
compatibility_date = "2025-02-04"
compatibility_flags = [ "nodejs_compat" ]
kv_namespaces = [
  { binding="ASSETS", id="471ada112ddd46eca4f652291d8f633e" }
]