name = "enforce-https"
main = "index.ts"
compatibility_date = "2025-02-04"
compatibility_flags = [ "nodejs_compat" ]
version_metadata.binding = "CF_VERSION_METADATA"
routes = [
  "http://nicholas.cloud/*",
  "http://*.nicholas.cloud/*"
]
secrets_store_secrets = [
  { store_id= "63609536ac1e446eb59160e3216e5f99", binding = "OTEL_EXPORTER_OTLP_ENDPOINT", secret_name = "otel-prod-endpoint" },
  { store_id= "63609536ac1e446eb59160e3216e5f99", binding = "OTEL_EXPORTER_OTLP_HEADERS", secret_name = "otel-prod-headers" }
]

[env.dev]
compatibility_date = "2025-02-04"
version_metadata.binding = "CF_VERSION_METADATA"
workers_dev = true
routes = []
secrets_store_secrets = [
  { store_id= "63609536ac1e446eb59160e3216e5f99", binding = "OTEL_EXPORTER_OTLP_ENDPOINT", secret_name = "otel-dev-endpoint" },
  { store_id= "63609536ac1e446eb59160e3216e5f99", binding = "OTEL_EXPORTER_OTLP_HEADERS", secret_name = "otel-dev-headers" }
]
